# Generated by Django 5.1.5 on 2025-02-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movieimg',
            field=models.ImageField(upload_to=''),
        ),
    ]
