# Generated by Django 5.1.5 on 2025-03-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationn', '0002_alter_movie_movieimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='movie',
            name='username',
            field=models.CharField(default='default_username', max_length=40),
        ),
    ]
