# Generated by Django 5.1.5 on 2025-03-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationn', '0003_movie_email_movie_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='movie',
            name='username',
            field=models.CharField(max_length=40),
        ),
    ]
